<a href="https://colab.research.google.com/github/GSaiSravani/sai/blob/main/ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv("fruit_dataset.csv")
df

fruit_label fruit_name  mass  width  height  color_score
0             1      apple   192    8.4     7.3         0.55
1             1      apple   180    8.0     6.8         0.59
2             1      apple   176    7.4     7.2         0.60
3             2   mandarin    86    6.2     4.7         0.80
4             2   mandarin    84    6.0     4.6         0.79
..          ...        ...   ...    ...     ...          ...
56            4      lemon   116    5.9     8.1         0.73
57            4      lemon   152    6.5     8.5         0.72
58            4      lemon   118    6.1     8.1         0.70
59            5      mango   113    7.1     7.2         0.72
60            5      mango   187    7.5     9.0         0.74

[61 rows x 6 columns]

In [ ]:
x=df.iloc[:,2:5].values
y=df.iloc[:,0].values
print(x)
print(y)

[[192.    8.4   7.3]
 [180.    8.    6.8]
 [176.    7.4   7.2]
 [ 86.    6.2   4.7]
 [ 84.    6.    4.6]
 [ 80.    5.8   4.3]
 [ 80.    5.9   4.3]
 [ 76.    5.8   4. ]
 [178.    7.1   7.8]
 [172.    7.4   7. ]
 [166.    6.9   7.3]
 [172.    7.1   7.6]
 [154.    7.    7.1]
 [164.    7.3   7.7]
 [152.    7.6   7.3]
 [156.    7.7   7.1]
 [156.    7.6   7.5]
 [168.    7.5   7.6]
 [162.    7.5   7.1]
 [162.    7.4   7.2]
 [160.    7.5   7.5]
 [156.    7.4   7.4]
 [140.    7.3   7.1]
 [170.    7.6   7.9]
 [342.    9.    9.4]
 [356.    9.2   9.2]
 [362.    9.6   9.2]
 [204.    7.5   9.2]
 [140.    6.7   7.1]
 [160.    7.    7.4]
 [158.    7.1   7.5]
 [210.    7.8   8. ]
 [164.    7.2   7. ]
 [190.    7.5   8.1]
 [142.    7.6   7.8]
 [150.    7.1   7.9]
 [160.    7.1   7.6]
 [154.    7.3   7.3]
 [158.    7.2   7.8]
 [144.    6.8   7.4]
 [154.    7.1   7.5]
 [180.    7.6   8.2]
 [154.    7.2   7.2]
 [194.    7.2  10.3]
 [200.    7.3  10.5]
 [186.    7.2   9.2]
 [216.    7.3  10.2]
 [196.    7.3

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.20,random_state=0)

In [ ]:
print("x train records",x_train.shape)
print("y train records",y_train.shape)
print("x test records",x_test.shape)
print("y test records",y_test.shape)

x train records (48, 3)
y train records (48,)
x test records (13, 3)
y test records (13,)


In [ ]:
from sklearn import tree
clf=tree.DecisionTreeClassifier(min_samples_split=2)
clf.fit(x_train,y_train)
pred_test=clf.predict(x_test)
print(pred_test)

[3 3 3 1 3 1 1 3 3 1 2 3 3]


In [ ]:
pred_train=clf.predict(x_train)
pred_train

array([3, 3, 4, 4, 2, 1, 3, 4, 3, 3, 4, 1, 4, 3, 1, 2, 3, 1, 4, 1, 4, 1,
       1, 3, 3, 1, 4, 4, 4, 3, 1, 1, 4, 3, 2, 1, 3, 4, 1, 1, 1, 3, 4, 2,
       1, 4, 4, 4])

In [ ]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,accuracy_score
print("Accuracy score on test data",accuracy_score(y_test,pred_test))
print("Accuracy score on train data",accuracy_score(y_train,pred_train))

Accuracy score on test data 0.5384615384615384
Accuracy score on train data 1.0


In [ ]:
df["fruit_name"].value_counts()

fruit_name
apple       19
orange      19
lemon       16
mandarin     5
mango        2
Name: count, dtype: int64

In [ ]:
df_1=pd.read_csv("fruit_dataset_increased1.csv")
df_1

fruit_label fruit_name  mass  width  height  color_score
0             1      apple   192    8.4     7.3         0.55
1             1      apple   180    8.0     6.8         0.59
2             1      apple   176    7.4     7.2         0.60
3             2   mandarin    86    6.2     4.7         0.80
4             2   mandarin    84    6.0     4.6         0.79
..          ...        ...   ...    ...     ...          ...
85            2   mandarin    80    5.8     4.3         0.77
86            2   mandarin    80    5.9     4.3         0.81
87            5      mango   187    7.5     9.0         0.74
88            5      mango   113    7.1     7.2         0.72
89            5      mango   187    7.5     9.0         0.74

[90 rows x 6 columns]

In [ ]:
df_1["fruit_name"].value_counts()

fruit_name
apple       19
orange      19
lemon       19
mango       19
mandarin    14
Name: count, dtype: int64

In [ ]:
x=df_1.iloc[:,2:5].values
y=df_1.iloc[:,0].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.20,random_state=0)

In [ ]:
print("x train records",x_train.shape)
print("y train records",y_train.shape)
print("x test records",x_test.shape)
print("y test records",y_test.shape)

x train records (72, 3)
y train records (72,)
x test records (18, 3)
y test records (18,)


In [ ]:
from sklearn import tree
clf=tree.DecisionTreeClassifier(min_samples_split=2)
clf.fit(x_train,y_train)
pred_test=clf.predict(x_test)
print(pred_test)

[1 3 4 1 5 3 4 4 5 5 2 3 1 2 1 1 3 4]


In [ ]:
pred_train=clf.predict(x_train)
pred_train

array([5, 3, 1, 2, 2, 4, 4, 4, 5, 5, 4, 2, 2, 5, 3, 1, 4, 4, 5, 5, 4, 2,
       1, 1, 3, 3, 2, 4, 5, 1, 3, 3, 1, 3, 1, 4, 1, 3, 5, 4, 5, 1, 3, 5,
       1, 2, 1, 3, 4, 5, 5, 5, 1, 2, 5, 3, 3, 4, 3, 2, 4, 1, 5, 3, 1, 2,
       1, 2, 5, 2, 4, 4])

In [ ]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,accuracy_score
print("Accuracy score on test data",accuracy_score(y_test,pred_test))
print("Accuracy score on train data",accuracy_score(y_train,pred_train))

Accuracy score on test data 0.8333333333333334
Accuracy score on train data 1.0
